#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

#----Config----#

bspc config border_width         0
bspc config window_gap           15

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config ignore_ewmh_focus true

#----Rules----#

# Permanent
bspc rule -a "Steam"              desktop=^6
bspc rule -a "discord"            desktop=^8
bspc rule -a "Tauon Music Box"    desktop=^9
bspc rule -a "Pavucontrol"        desktop=^10
bspc rule -a "QjackCtl"           desktop=^10

bspc rule -a "ark"                floating=on

#----Mouse----#

bspc config pointer_modifier mod3
bspc config pointer_action1 move

#----Autostart----#

# Config stuff
setxkbmap br &
xmodmap ~/.Xmodmap &
sxkhd -c $HOME/.config/sxhkd/sxhkdrc &
sh $HOME/.config/polybar/launch.sh
feh --bg-fill /mnt/Hub/Archive/Wallpapers/lain2.jpg
dunst &
lxsession &


# Sound
#pipewire &
#wireplumber &
#qjackctl &
#carla &

# Programs
xrdb -load "$HOME/.Xresources" 
st &
pavucontrol &
tauon &
picom &
flameshot &
fcitx &
